### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by benrose207** [benrose207/AllHikes#8]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Users can sign up, sign in, and log out
- [x] Users can use a demo login to access the site without creating a new account

**Comment by benrose207** [comment]
@linakherchi, assigning this over to you to review the basic User Auth feature for my project. Let me know if you have any feedback!

**Comment by linakherchi** [comment]
@benrose207 Good job ! Smooth navigation and simple and clear presentation. 
I really enjoyed your small pop-up that shows up when the password length is not valid or when you do not pass in a username when trying to signup and I am really curious to see how you created those. 
A couple of comments here: 

- It would be preferable if your Github/Linkedin links open up a new tab for the visitor instead of changing the URL of the page you are in. I think you would just need to add a property in your a tag in order to achieve this purpose.
- When I log in/ sign up, and try to go to my profile, it seems like you have duplicate 'profile'. I don't know if it is on purpose but wanted to leave a note in case it was not. 

Other than that you have done a wonderful job for your first feature !

**Comment by benrose207** [comment]
@linakherchi , thanks so much, I'm so glad to hear it!! To your few points:

- I was actually able to set the form validation pop-ups super easily using some built-in HTML attributes! Found a good resource on MDN for it, and they seemed to work well. 
- Opening those links in a new tab should be fixed now! 
- The two different Profile headings is something I'm aware of. Ultimately I'm planning on adding Reviews and Photos tabs to the profile page, so that the top "Profile" you see will be part of a tab system, and the bottom one will dynamically show the current page the user has selected: https://share.getcloudapp.com/2Nu5lkmA

Let me know if that makes sense! One small question regarding the Github link: is it better to link to my general GitHub page there, or to the specific page for this project's repo?

**Comment by linakherchi** [comment]
Great ! Thank you.

We usually use the Github logo to redirect the visitor to the user's Github profile. But adding another link a the bottom of the page that redirects the visitor to the actual repository is a great idea that you can implement !
